apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plowered.fullname" . }}-config
  labels: {{- include "plowered.labels" . | nindent 4 }}
data:
  PLOWERED_ENV:                   {{ .Values.config.env | quote }}
  PLOWERED_VERSION:               {{ .Chart.AppVersion | quote }}
  PLOWERED_GRPC_ADDR:             ":{{ .Values.service.grpcPort }}"
  PLOWERED_HTTP_ADDR:             ":{{ .Values.service.httpPort }}"
  PLOWERED_SHUTDOWN_GRACE:        {{ .Values.config.shutdownGrace | quote }}
  PLOWERED_JWT_ISSUER:            {{ .Values.config.jwt.issuer | quote }}
  PLOWERED_JWT_AUDIENCE:          {{ .Values.config.jwt.audience | quote }}
  PLOWERED_RATE_LIMIT_PER_SECOND: {{ .Values.config.rateLimit.perSecond | quote }}
  PLOWERED_RATE_LIMIT_BURST:      {{ .Values.config.rateLimit.burst | quote }}
  PLOWERED_CORS_ALLOWED_ORIGINS:  {{ .Values.config.cors.allowedOrigins | quote }}
