{{- if not .Values.secrets.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plowered.secretName" . }}
  labels: {{- include "plowered.labels" . | nindent 4 }}
type: Opaque
stringData:
  PLOWERED_DATABASE_URL:    {{ .Values.secrets.values.databaseUrl | quote }}
  PLOWERED_JWT_HS256_SECRET: {{ .Values.secrets.values.jwtHs256Secret | quote }}
  PLOWERED_JWT_RS256_PUB_KEY: {{ .Values.secrets.values.jwtRs256PublicKey | quote }}
{{- end -}}
